"""
Data Export API Routes
"""
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse, JSONResponse
from datetime import datetime
import io
import csv
import json

from services.data_service import data_service
from config import settings

router = APIRouter()


@router.get("/csv")
async def export_csv():
    """
    Export traffic data as CSV file.
    
    Returns:
        CSV file download
    """
    if not data_service.is_loaded:
        raise HTTPException(status_code=503, detail="Data not loaded")
    
    # Create CSV in memory
    output = io.StringIO()
    writer = csv.writer(output)
    
    # Write header
    writer.writerow(['minute', 'vehicle', 'count', 'timestamp'])
    
    # Write data with timestamp
    base_time = datetime.now().replace(second=0, microsecond=0)
    for _, row in data_service.df.iterrows():
        timestamp = base_time.replace(minute=int(row['minute']) % 60)
        writer.writerow([
            int(row['minute']),
            row['vehicle'],
            int(row['count']),
            timestamp.isoformat(),
        ])
    
    # Prepare response
    output.seek(0)
    filename = f"traffic_data_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
    
    return StreamingResponse(
        iter([output.getvalue()]),
        media_type="text/csv",
        headers={
            "Content-Disposition": f"attachment; filename={filename}",
        },
    )


@router.get("/json")
async def export_json():
    """
    Export traffic data as JSON file.
    
    Returns:
        JSON file download
    """
    if not data_service.is_loaded:
        raise HTTPException(status_code=503, detail="Data not loaded")
    
    # Prepare comprehensive export data
    export_data = {
        "metadata": {
            "export_date": datetime.now().isoformat(),
            "location": {
                "name": settings.location_name,
                "latitude": settings.latitude,
                "longitude": settings.longitude,
                "camera_id": settings.camera_id,
            },
            "data_version": "1.0",
        },
        "summary": data_service.get_summary(),
        "categories": data_service.get_categories(),
        "timeseries": data_service.get_timeseries(),
        "peak_analysis": data_service.get_peak_analysis(),
    }
    
    # Convert to JSON string
    json_str = json.dumps(export_data, indent=2)
    filename = f"traffic_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    
    return StreamingResponse(
        iter([json_str]),
        media_type="application/json",
        headers={
            "Content-Disposition": f"attachment; filename={filename}",
        },
    )


@router.get("/report")
async def generate_report():
    """
    Generate a formatted traffic analysis report.
    
    Returns:
        Markdown formatted report
    """
    if not data_service.is_loaded:
        raise HTTPException(status_code=503, detail="Data not loaded")
    
    summary = data_service.get_summary()
    categories = data_service.get_categories()
    peak = data_service.get_peak_analysis()
    
    report = f"""# Traffic Analysis Report
    
## Location Information
- **Location:** {settings.location_name}
- **Coordinates:** {settings.latitude}, {settings.longitude}
- **Camera ID:** {settings.camera_id}
- **Report Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Executive Summary

During the monitoring period of **{summary['duration_minutes']} minutes**, a total of **{summary['total_vehicles']:,}** vehicles were detected and tracked.

### Key Metrics
| Metric | Value |
|--------|-------|
| Total Vehicles | {summary['total_vehicles']:,} |
| Average per Minute | {summary['average_per_minute']:.1f} |
| Peak Minute | Minute {summary['peak_minute']} |
| Peak Count | {summary['peak_count']:,} vehicles |

## Vehicle Composition

"""
    
    for cat in categories['categories']:
        report += f"- **{cat['category']}**: {cat['count']:,} ({cat['percentage']:.1f}%)\n"
    
    report += f"""
## Traffic Patterns

### Peak Analysis
- Peak threshold: {peak['peak_threshold']} vehicles/minute
- Number of peak minutes: {len(peak['peak_minutes'])}

### Time Period Breakdown
- **Early Period**: {peak['morning_rush']['total']:,} vehicles (avg: {peak['morning_rush']['average']:.1f}/min)
- **Late Period**: {peak['evening_rush']['total']:,} vehicles (avg: {peak['evening_rush']['average']:.1f}/min)

## Recommendations

1. Consider traffic signal optimization during peak minute {summary['peak_minute']}
2. Monitor truck traffic during high-density periods
3. Evaluate pedestrian safety during peak hours

---
*Generated by Traffic AI Dashboard*
"""
    
    filename = f"traffic_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    
    return StreamingResponse(
        iter([report]),
        media_type="text/markdown",
        headers={
            "Content-Disposition": f"attachment; filename={filename}",
        },
    )
